#!/usr/bin/perl
#
# generovani vstupniho spuboru 'odkazy.txt'
#
# options
#   -w  - generovat soubor 'odkazy.txt'
#   -p  - pololeti
#   -s  - skolni rok
#
use lib "/home/rusek/lib/";
use DBI;
use locale;
use CommonPgC;
use Mkrec;
use Getopt::Std;

sub printFile {	
	my ($file,$type) = @_;
	$time = localtime();
	open( LINKS,">$file" );
	# vypis pole %obor
	print  LINKS "#--------------------------------------------------------- \n";
	print  LINKS "# Generated by mklinks.pl at $time\n";
	print  LINKS "#---------------------------------------------------------\n";
	foreach $num_obor ( sort keys %obor ) {
		if($type eq "2") {
			print LINKS "#--- OBOR $num_obor ---\n$num_obor:";
		} else {
			print LINKS "!$num_obor --------- OBOROVA SKUPINA ---------\n";
		}
		$newline = "";
		foreach $r ( sort @{$obor{$num_obor}} ) {
			if($type eq "2") {
				($id_akce) = split(/:/,$r);
				$newline .= "$id_akce,";
			} else {
				print  LINKS "$r\n"
			}
		}
		if($type eq "2") {
			$newline =~ s/\n//g;
			$newline =~ s/\r//g; 
			print LINKS substr($newline,0,-1)."\n";
		}
	}
	print LINKS "#---- END ----\n";
	close LINKS;
}

#---------------- inicializace ----------------
	$dir = "./";
	$odkazy = $dir."odkazy.txt";
	$links = $dir."links.txt";
	%links = ();
	%obor = ();

	getopts("p:s:w");
	$skrok = $opt_s;
	$polo  = $opt_p;

	print "Hello, I'm makeing links\n";
	$db = DBI->connect("$db_host_port;$mysql_sock",$user,$passw) or die "Nelze otevøít databázi: ".DBI->errstr."\n";
	$q_garant = $db->prepare("SELECT * FROM zam ORDER BY prijmeni");
	$q_garant->execute();
	#$a = getAkceName('412202',$db,$skrok,$polo);

	open(LINKS,$links);
	while($line=<LINKS>) {
		chomp($line);
		if(substr($line,0,1) ne "#") {
			if(substr($line,0,1) eq "!") {
				# zaciname novou oborovou skupinu
				$num_obor = substr($line,1,2);
			} else {
				# zpracovani radku
				print "line: $line\n";
				($id_akce,$id_kurz,$nazev) = split(/:/,$line);
				if($id_akce ne "" && $id_kurz ne "") {
					# kontrola - doplnit nazev
					($id_akce_test,$id_kurz) = id_akce_kurz($id_akce,$id_kurz,$db,$skrok,$polo);
					if($id_akce_test ne $id_akce) {
						$id_akce = $id_akce_test;
						print "--> updated";
					} else {
						print "--> OK";
					}
				} else {
					($id_akce,$id_kurz) = id_akce_kurz($id_akce,$id_kurz,$db,$skrok,$polo);
					print "--> completed";
				}
				$nazev = getAkceName($id_akce,$db,$skrok,$polo);
				$nazev =~ s/\n//g;
				$nazev =~ s/\r//g;
				print " ($id_akce:$id_kurz:$nazev)\n\n";
				$line = join(":",($id_akce,$id_kurz,$nazev));
				push @{$obor{$num_obor}},$line;
			}
		}
	}
	close(LINKS);
	# kontrolni tisky na obr.
	#printFile("-",1);
	#printFile("-",2);
	if($opt_w){
		print "...creating backups\n";
		system("mv $odkazy $odkazy.backup");
		system("mv $links $links.backup");
		print "...writing new file '$links'\n";
		printFile($links,1);
		print "...writing new file '$odkazy'\n";
		printFile($odkazy,2);
		print "Done.\n";
	}


